### ISSUE TITLE
沒有345000000G-000001這筆資料，但確要下載345000000G-000001-001?

### ISSUE THREAD

**Issue by ogre0403** [ogre0403/ipgod#18]
2016-12-30 11:07:11,024 [ERROR] Downloader.py_27  : Download 345000000G-000001-001 ERROR!!!
Traceback (most recent call last):
  File "/opt/ipgod_production/crawler/src/Downloader.py", line 25, in run
    self.download_flag = item.download()
  File "/opt/ipgod_production/crawler/src/metadata.py", line 151, in download
    with open(file_name, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/ipgod/data_download/345000000G-000001/345000000G-000001-001.json'

**Comment by ogre0403** [comment]
猜測原因：
可能是有些資料集裡的distribution裡的resource是寫成345000000G-000001，而不是和實際的資料集id做對應。
